// Package registertypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package registertypes

import (
	"time"
)

// Defines values for AdvisorySeverity.
const (
	Critical AdvisorySeverity = "critical"
	High     AdvisorySeverity = "high"
	Low      AdvisorySeverity = "low"
	Medium   AdvisorySeverity = "medium"
	Unknown  AdvisorySeverity = "unknown"
)

// Valid indicates whether the value is a known member of the AdvisorySeverity enum.
func (e AdvisorySeverity) Valid() bool {
	switch e {
	case Critical:
		return true
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for DeprecationReason.
const (
	NoFix DeprecationReason = "no-fix"
	Stale DeprecationReason = "stale"
)

// Valid indicates whether the value is a known member of the DeprecationReason enum.
func (e DeprecationReason) Valid() bool {
	switch e {
	case NoFix:
		return true
	case Stale:
		return true
	default:
		return false
	}
}

// Defines values for Outcome.
const (
	Clean       Outcome = "clean"
	Findings    Outcome = "findings"
	NotFound    Outcome = "not-found"
	Unreachable Outcome = "unreachable"
)

// Valid indicates whether the value is a known member of the Outcome enum.
func (e Outcome) Valid() bool {
	switch e {
	case Clean:
		return true
	case Findings:
		return true
	case NotFound:
		return true
	case Unreachable:
		return true
	default:
		return false
	}
}

// Defines values for RequestEcosystem.
const (
	RequestEcosystemGo         RequestEcosystem = "go"
	RequestEcosystemInternal   RequestEcosystem = "internal"
	RequestEcosystemPython     RequestEcosystem = "python"
	RequestEcosystemRust       RequestEcosystem = "rust"
	RequestEcosystemTypescript RequestEcosystem = "typescript"
)

// Valid indicates whether the value is a known member of the RequestEcosystem enum.
func (e RequestEcosystem) Valid() bool {
	switch e {
	case RequestEcosystemGo:
		return true
	case RequestEcosystemInternal:
		return true
	case RequestEcosystemPython:
		return true
	case RequestEcosystemRust:
		return true
	case RequestEcosystemTypescript:
		return true
	default:
		return false
	}
}

// Defines values for RequestType.
const (
	Admission RequestType = "admission"
	OpenTrack RequestType = "open-track"
	Upgrade   RequestType = "upgrade"
)

// Valid indicates whether the value is a known member of the RequestType enum.
func (e RequestType) Valid() bool {
	switch e {
	case Admission:
		return true
	case OpenTrack:
		return true
	case Upgrade:
		return true
	default:
		return false
	}
}

// Defines values for TrackEcosystem.
const (
	TrackEcosystemGo         TrackEcosystem = "go"
	TrackEcosystemInternal   TrackEcosystem = "internal"
	TrackEcosystemPython     TrackEcosystem = "python"
	TrackEcosystemRust       TrackEcosystem = "rust"
	TrackEcosystemTypescript TrackEcosystem = "typescript"
)

// Valid indicates whether the value is a known member of the TrackEcosystem enum.
func (e TrackEcosystem) Valid() bool {
	switch e {
	case TrackEcosystemGo:
		return true
	case TrackEcosystemInternal:
		return true
	case TrackEcosystemPython:
		return true
	case TrackEcosystemRust:
		return true
	case TrackEcosystemTypescript:
		return true
	default:
		return false
	}
}

// Defines values for VerdictCode.
const (
	Adopted                  VerdictCode = "adopted"
	DeniedNotAMaintainedLine VerdictCode = "denied-not-a-maintained-line"
	DeniedOverBudget         VerdictCode = "denied-over-budget"
	DeniedOverFloor          VerdictCode = "denied-over-floor"
	DeniedQuarantined        VerdictCode = "denied-quarantined"
	DeniedSecurityRegression VerdictCode = "denied-security-regression"
	DeniedUnknownVersion     VerdictCode = "denied-unknown-version"
	HeldCanaryRed            VerdictCode = "held-canary-red"
	HeldQuarantined          VerdictCode = "held-quarantined"
	HeldWorseVector          VerdictCode = "held-worse-vector"
	PendingAdmission         VerdictCode = "pending-admission"
	UpToDate                 VerdictCode = "up-to-date"
)

// Valid indicates whether the value is a known member of the VerdictCode enum.
func (e VerdictCode) Valid() bool {
	switch e {
	case Adopted:
		return true
	case DeniedNotAMaintainedLine:
		return true
	case DeniedOverBudget:
		return true
	case DeniedOverFloor:
		return true
	case DeniedQuarantined:
		return true
	case DeniedSecurityRegression:
		return true
	case DeniedUnknownVersion:
		return true
	case HeldCanaryRed:
		return true
	case HeldQuarantined:
		return true
	case HeldWorseVector:
		return true
	case PendingAdmission:
		return true
	case UpToDate:
		return true
	default:
		return false
	}
}

// Defines values for VerdictEcosystem.
const (
	VerdictEcosystemGo         VerdictEcosystem = "go"
	VerdictEcosystemInternal   VerdictEcosystem = "internal"
	VerdictEcosystemPython     VerdictEcosystem = "python"
	VerdictEcosystemRust       VerdictEcosystem = "rust"
	VerdictEcosystemTypescript VerdictEcosystem = "typescript"
)

// Valid indicates whether the value is a known member of the VerdictEcosystem enum.
func (e VerdictEcosystem) Valid() bool {
	switch e {
	case VerdictEcosystemGo:
		return true
	case VerdictEcosystemInternal:
		return true
	case VerdictEcosystemPython:
		return true
	case VerdictEcosystemRust:
		return true
	case VerdictEcosystemTypescript:
		return true
	default:
		return false
	}
}

// Advisory The current version carries a vulnerability. An advisory pierces every pin - a consumer that resolved an advised version fails loud, hard-pinned or not - and is cleared only by acknowledging the named ids in the consumer's own factory file.
//
// It carries what a consumer needs to decide, because the alternative is a consumer asserting things it never checked. "no fix upstream" was printed for a year by code that had never read a range event.
type Advisory struct {
	// AffectedImports The import paths the advisory is scoped to, where the ecosystem publishes them. Empty means the feed gave no scope, NOT that everything is affected. A consumer can use this to see whether its own code goes anywhere near the vulnerable part.
	AffectedImports *[]string `json:"affectedImports,omitempty"`

	// FixedIn The versions the feed names as fixing this, unioned across the named ids. Empty means the feed names none, which is a fact read from the record rather than an assumption. Upgrading is the best way out of an advisory, so a consumer has to be told when one exists.
	FixedIn *[]string `json:"fixedIn,omitempty"`

	// Severity The highest severity among the vulnerabilities named. "unknown" when the feed publishes none anywhere, which is 38 percent of real records - saying so beats inventing a number.
	Severity AdvisorySeverity `json:"severity"`

	// Since When the advisory was published upstream, not when this pipeline noticed it. It is also what arms auto-deprecation, so the pipeline's own clock would deprecate a track early.
	Since   time.Time `json:"since"`
	VulnIds []string  `json:"vulnIds"`
}

// AdvisorySeverity The highest severity among the vulnerabilities named. "unknown" when the feed publishes none anywhere, which is 38 percent of real records - saying so beats inventing a number.
type AdvisorySeverity string

// Alternative A version a denial offers instead, with its vector.
type Alternative struct {
	ReleasedAt *time.Time `json:"releasedAt,omitempty"`
	Version    string     `json:"version"`

	// Vulns Counts of known, unfixed vulnerabilities affecting one version, by severity. Vectors compare lexicographically from critical down, so a critical never trades against any number of lows. A vulnerability with unknown severity counts as high.
	Vulns SeverityVector `json:"vulns"`
}

// Deprecation Set by register policy, never by hand. A track deprecates when its advisory has no fix past the deprecation window, or when upstream stopped releasing into it while a successor exists.
type Deprecation struct {
	Reason DeprecationReason `json:"reason"`
	Since  time.Time         `json:"since"`
}

// DeprecationReason defines model for Deprecation.Reason.
type DeprecationReason string

// Outcome What actually happened when the vulnerability feed was asked. It exists because three different situations all answer HTTP 200 with the body "{}": a package with no vulnerabilities, a package the feed has never heard of, and a request the feed could not read. Recording only a count of zero turned all three into the claim "this is clean".
//
// findings - a published range covers this version.
// clean - the feed answered and no range covers this version.
// not-found - the feed carries no record for this package at all.
// unreachable - the request failed, so nothing was measured.
type Outcome string

// Request The only door into the register. A request is untrusted input; it moves the register only by passing the same policy as everything else, whoever files it. An open-track request derives from a consumer factory declaration, never from a CLI.
type Request struct {
	CreatedAt time.Time        `json:"createdAt"`
	Ecosystem RequestEcosystem `json:"ecosystem"`
	Package   string           `json:"package"`

	// Reason Mandatory. A request with no reason is a config error.
	Reason string `json:"reason"`

	// Requester Who filed it. A consumer name, or a person.
	Requester *string `json:"requester,omitempty"`

	// Track Required for open-track, optional otherwise.
	Track *string     `json:"track,omitempty"`
	Type  RequestType `json:"type"`

	// Version An exact version, when the requester wants one. Absent, the admission algorithm chooses and never substitutes silently.
	Version *string `json:"version,omitempty"`
}

// RequestEcosystem defines model for Request.Ecosystem.
type RequestEcosystem string

// RequestType defines model for Request.Type.
type RequestType string

// SeverityVector Counts of known, unfixed vulnerabilities affecting one version, by severity. Vectors compare lexicographically from critical down, so a critical never trades against any number of lows. A vulnerability with unknown severity counts as high.
type SeverityVector struct {
	Critical int `json:"critical"`
	High     int `json:"high"`
	Low      int `json:"low"`
	Medium   int `json:"medium"`
}

// Spec Engine specific configuration. The core model fixes the shape of the register documents. Each engine keeps this block for its own internals, so register-state-git takes a path and a DynamoDB engine takes a table and a region, and nothing in the core model knows about either.
type Spec map[string]interface{}

// Track A maintained line of one package, named by a semver prefix. One current version per track. A version belongs to its longest matching track prefix. One index file per track, and this is that file's shape.
//
// The file carries current state only. The register lives in a git repository, so git already records every version this file ever held along with the commit that caused each change; a history array inside the file restated what `git log -p` gives for free, and drifted from it. Unknown keys are refused so one cannot creep back in.
type Track struct {
	// AdoptedAt When the register adopted the current version.
	AdoptedAt *time.Time `json:"adoptedAt,omitempty"`

	// Advisory The current version carries a vulnerability. An advisory pierces every pin - a consumer that resolved an advised version fails loud, hard-pinned or not - and is cleared only by acknowledging the named ids in the consumer's own factory file.
	//
	// It carries what a consumer needs to decide, because the alternative is a consumer asserting things it never checked. "no fix upstream" was printed for a year by code that had never read a range event.
	Advisory *Advisory `json:"advisory,omitempty"`
	Current  string    `json:"current"`

	// Deprecated Set by register policy, never by hand. A track deprecates when its advisory has no fix past the deprecation window, or when upstream stopped releasing into it while a successor exists.
	Deprecated *Deprecation   `json:"deprecated,omitempty"`
	Ecosystem  TrackEcosystem `json:"ecosystem"`

	// OsvSnapshot Digest of the vulnerability snapshot behind the adopting verdict, so the decision replays and explains itself. The digest of an empty snapshot is the sha256 of nothing, which is why outcome is recorded beside it rather than inferred from it.
	OsvSnapshot *string `json:"osvSnapshot,omitempty"`

	// Outcome What actually happened when the vulnerability feed was asked. It exists because three different situations all answer HTTP 200 with the body "{}": a package with no vulnerabilities, a package the feed has never heard of, and a request the feed could not read. Recording only a count of zero turned all three into the claim "this is clean".
	//
	// findings - a published range covers this version.
	// clean - the feed answered and no range covers this version.
	// not-found - the feed carries no record for this package at all.
	// unreachable - the request failed, so nothing was measured.
	Outcome Outcome `json:"outcome"`

	// Package The package URL, go-import style.
	Package string `json:"package"`

	// Prefix "1" for a major track, "1.27" for a maintained line.
	Prefix string `json:"prefix"`

	// Provenance The revision id that proved an internal package, minted by the pipeline that released it. Absent for external packages, which enter by policy rather than proof.
	Provenance *string `json:"provenance,omitempty"`

	// QuietSince Set by register policy, never by hand: upstream's last release into this track, once the track has been quiet past the stale window with no successor line to deprecate toward. The track stays current - silence with nowhere to go is a fact worth naming, not a retirement - and the mark clears the moment upstream releases again or a successor appears.
	QuietSince *time.Time `json:"quietSince,omitempty"`

	// Reason Why the vector says what it says, in words, for a person reading this file later. A zero vector means nothing on its own: the feed answered and found nothing, or the feed does not carry this package, or the feed could not be reached. This sentence is what tells those apart at a glance.
	Reason *string `json:"reason,omitempty"`

	// ReleasedAt When upstream published the current version.
	ReleasedAt *time.Time `json:"releasedAt,omitempty"`

	// Source Where the artifact comes from. Registry coordinates for an external package, a git URL for an internal one.
	Source    *string   `json:"source,omitempty"`
	UpdatedAt time.Time `json:"updatedAt"`

	// Vulns Counts of known, unfixed vulnerabilities affecting one version, by severity. Vectors compare lexicographically from critical down, so a critical never trades against any number of lows. A vulnerability with unknown severity counts as high.
	Vulns SeverityVector `json:"vulns"`
}

// TrackEcosystem defines model for Track.Ecosystem.
type TrackEcosystem string

// Verdict Every decision the register takes, written with its inputs. Not upgrading is never silent, and a rejection is structured so a person or an agent can correct the next request from the verdict alone.
type Verdict struct {
	// Adopted The version an adoption settled on.
	Adopted *string `json:"adopted,omitempty"`

	// Alternatives What a denial offers instead.
	Alternatives *[]Alternative    `json:"alternatives,omitempty"`
	Code         VerdictCode       `json:"code"`
	DecidedAt    time.Time         `json:"decidedAt"`
	Ecosystem    *VerdictEcosystem `json:"ecosystem,omitempty"`

	// Message The human half. A denial must carry one.
	Message     *string `json:"message,omitempty"`
	OsvSnapshot *string `json:"osvSnapshot,omitempty"`
	Package     string  `json:"package"`

	// Requested The exact version the request named, when it named one.
	Requested *string `json:"requested,omitempty"`
	Track     *string `json:"track,omitempty"`
}

// VerdictCode defines model for Verdict.Code.
type VerdictCode string

// VerdictEcosystem defines model for Verdict.Ecosystem.
type VerdictEcosystem string
