// Package registertypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package registertypes

import (
	"time"
)

// Defines values for AdvisorySeverity.
const (
	Critical AdvisorySeverity = "critical"
	High     AdvisorySeverity = "high"
	Low      AdvisorySeverity = "low"
	Medium   AdvisorySeverity = "medium"
)

// Valid indicates whether the value is a known member of the AdvisorySeverity enum.
func (e AdvisorySeverity) Valid() bool {
	switch e {
	case Critical:
		return true
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for DeprecationReason.
const (
	NoFix DeprecationReason = "no-fix"
	Stale DeprecationReason = "stale"
)

// Valid indicates whether the value is a known member of the DeprecationReason enum.
func (e DeprecationReason) Valid() bool {
	switch e {
	case NoFix:
		return true
	case Stale:
		return true
	default:
		return false
	}
}

// Defines values for RequestEcosystem.
const (
	RequestEcosystemGo         RequestEcosystem = "go"
	RequestEcosystemInternal   RequestEcosystem = "internal"
	RequestEcosystemPython     RequestEcosystem = "python"
	RequestEcosystemRust       RequestEcosystem = "rust"
	RequestEcosystemTypescript RequestEcosystem = "typescript"
)

// Valid indicates whether the value is a known member of the RequestEcosystem enum.
func (e RequestEcosystem) Valid() bool {
	switch e {
	case RequestEcosystemGo:
		return true
	case RequestEcosystemInternal:
		return true
	case RequestEcosystemPython:
		return true
	case RequestEcosystemRust:
		return true
	case RequestEcosystemTypescript:
		return true
	default:
		return false
	}
}

// Defines values for RequestType.
const (
	Admission RequestType = "admission"
	OpenTrack RequestType = "open-track"
	Upgrade   RequestType = "upgrade"
)

// Valid indicates whether the value is a known member of the RequestType enum.
func (e RequestType) Valid() bool {
	switch e {
	case Admission:
		return true
	case OpenTrack:
		return true
	case Upgrade:
		return true
	default:
		return false
	}
}

// Defines values for TrackEcosystem.
const (
	TrackEcosystemGo         TrackEcosystem = "go"
	TrackEcosystemInternal   TrackEcosystem = "internal"
	TrackEcosystemPython     TrackEcosystem = "python"
	TrackEcosystemRust       TrackEcosystem = "rust"
	TrackEcosystemTypescript TrackEcosystem = "typescript"
)

// Valid indicates whether the value is a known member of the TrackEcosystem enum.
func (e TrackEcosystem) Valid() bool {
	switch e {
	case TrackEcosystemGo:
		return true
	case TrackEcosystemInternal:
		return true
	case TrackEcosystemPython:
		return true
	case TrackEcosystemRust:
		return true
	case TrackEcosystemTypescript:
		return true
	default:
		return false
	}
}

// Defines values for VerdictCode.
const (
	Adopted                  VerdictCode = "adopted"
	DeniedNotAMaintainedLine VerdictCode = "denied-not-a-maintained-line"
	DeniedOverBudget         VerdictCode = "denied-over-budget"
	DeniedOverFloor          VerdictCode = "denied-over-floor"
	DeniedQuarantined        VerdictCode = "denied-quarantined"
	DeniedSecurityRegression VerdictCode = "denied-security-regression"
	HeldCanaryRed            VerdictCode = "held-canary-red"
	HeldWorseVector          VerdictCode = "held-worse-vector"
	PendingAdmission         VerdictCode = "pending-admission"
)

// Valid indicates whether the value is a known member of the VerdictCode enum.
func (e VerdictCode) Valid() bool {
	switch e {
	case Adopted:
		return true
	case DeniedNotAMaintainedLine:
		return true
	case DeniedOverBudget:
		return true
	case DeniedOverFloor:
		return true
	case DeniedQuarantined:
		return true
	case DeniedSecurityRegression:
		return true
	case HeldCanaryRed:
		return true
	case HeldWorseVector:
		return true
	case PendingAdmission:
		return true
	default:
		return false
	}
}

// Defines values for VerdictEcosystem.
const (
	VerdictEcosystemGo         VerdictEcosystem = "go"
	VerdictEcosystemInternal   VerdictEcosystem = "internal"
	VerdictEcosystemPython     VerdictEcosystem = "python"
	VerdictEcosystemRust       VerdictEcosystem = "rust"
	VerdictEcosystemTypescript VerdictEcosystem = "typescript"
)

// Valid indicates whether the value is a known member of the VerdictEcosystem enum.
func (e VerdictEcosystem) Valid() bool {
	switch e {
	case VerdictEcosystemGo:
		return true
	case VerdictEcosystemInternal:
		return true
	case VerdictEcosystemPython:
		return true
	case VerdictEcosystemRust:
		return true
	case VerdictEcosystemTypescript:
		return true
	default:
		return false
	}
}

// Advisory The current version carries a vulnerability and no fixed version exists upstream yet. An advisory pierces every pin - a consumer that resolved an advised version fails loud, hard-pinned or not.
type Advisory struct {
	// Severity The highest severity among the vulnerabilities named.
	Severity AdvisorySeverity `json:"severity"`
	Since    time.Time        `json:"since"`
	VulnIds  []string         `json:"vulnIds"`
}

// AdvisorySeverity The highest severity among the vulnerabilities named.
type AdvisorySeverity string

// Alternative A version a denial offers instead, with its vector.
type Alternative struct {
	ReleasedAt *time.Time `json:"releasedAt,omitempty"`
	Version    string     `json:"version"`

	// Vulns Counts of known, unfixed vulnerabilities affecting one version, by severity. Vectors compare lexicographically from critical down, so a critical never trades against any number of lows. A vulnerability with unknown severity counts as high.
	Vulns SeverityVector `json:"vulns"`
}

// Deprecation Set by register policy, never by hand. A track deprecates when its advisory has no fix past the deprecation window, or when upstream stopped releasing into it while a successor exists.
type Deprecation struct {
	Reason DeprecationReason `json:"reason"`
	Since  time.Time         `json:"since"`
}

// DeprecationReason defines model for Deprecation.Reason.
type DeprecationReason string

// Request The only door into the register. A request is untrusted input; it moves the register only by passing the same policy as everything else, whoever files it. An open-track request derives from a consumer factory declaration, never from a CLI.
type Request struct {
	CreatedAt time.Time        `json:"createdAt"`
	Ecosystem RequestEcosystem `json:"ecosystem"`
	Package   string           `json:"package"`

	// Reason Mandatory. A request with no reason is a config error.
	Reason string `json:"reason"`

	// Requester Who filed it. A consumer name, or a person.
	Requester *string `json:"requester,omitempty"`

	// Track Required for open-track, optional otherwise.
	Track *string     `json:"track,omitempty"`
	Type  RequestType `json:"type"`

	// Version An exact version, when the requester wants one. Absent, the admission algorithm chooses and never substitutes silently.
	Version *string `json:"version,omitempty"`
}

// RequestEcosystem defines model for Request.Ecosystem.
type RequestEcosystem string

// RequestType defines model for Request.Type.
type RequestType string

// SeverityVector Counts of known, unfixed vulnerabilities affecting one version, by severity. Vectors compare lexicographically from critical down, so a critical never trades against any number of lows. A vulnerability with unknown severity counts as high.
type SeverityVector struct {
	Critical int `json:"critical"`
	High     int `json:"high"`
	Low      int `json:"low"`
	Medium   int `json:"medium"`
}

// Spec Engine specific configuration. The core model fixes the shape of the register documents. Each engine keeps this block for its own internals, so register-state-git takes a path and a DynamoDB engine takes a table and a region, and nothing in the core model knows about either.
type Spec map[string]interface{}

// Track A maintained line of one package, named by a semver prefix. One current version per track. A version belongs to its longest matching track prefix. One index file per track, and this is that file's shape.
type Track struct {
	// Advisory The current version carries a vulnerability and no fixed version exists upstream yet. An advisory pierces every pin - a consumer that resolved an advised version fails loud, hard-pinned or not.
	Advisory *Advisory `json:"advisory,omitempty"`
	Current  string    `json:"current"`

	// Deprecated Set by register policy, never by hand. A track deprecates when its advisory has no fix past the deprecation window, or when upstream stopped releasing into it while a successor exists.
	Deprecated *Deprecation   `json:"deprecated,omitempty"`
	Ecosystem  TrackEcosystem `json:"ecosystem"`

	// History Adopted versions, oldest first. current is the last.
	History *[]VersionEntry `json:"history,omitempty"`

	// Package The package URL, go-import style.
	Package string `json:"package"`

	// Prefix "1" for a major track, "1.27" for a maintained line.
	Prefix    string    `json:"prefix"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// TrackEcosystem defines model for Track.Ecosystem.
type TrackEcosystem string

// Verdict Every decision the register takes, written with its inputs. Not upgrading is never silent, and a rejection is structured so a person or an agent can correct the next request from the verdict alone.
type Verdict struct {
	// Adopted The version an adoption settled on.
	Adopted *string `json:"adopted,omitempty"`

	// Alternatives What a denial offers instead.
	Alternatives *[]Alternative    `json:"alternatives,omitempty"`
	Code         VerdictCode       `json:"code"`
	DecidedAt    time.Time         `json:"decidedAt"`
	Ecosystem    *VerdictEcosystem `json:"ecosystem,omitempty"`

	// Message The human half. A denial must carry one.
	Message     *string `json:"message,omitempty"`
	OsvSnapshot *string `json:"osvSnapshot,omitempty"`
	Package     string  `json:"package"`

	// Requested The exact version the request named, when it named one.
	Requested *string `json:"requested,omitempty"`
	Track     *string `json:"track,omitempty"`
}

// VerdictCode defines model for Verdict.Code.
type VerdictCode string

// VerdictEcosystem defines model for Verdict.Ecosystem.
type VerdictEcosystem string

// VersionEntry One adopted version in a track's history.
type VersionEntry struct {
	// AdoptedAt When the register adopted it.
	AdoptedAt time.Time `json:"adoptedAt"`

	// OsvSnapshot Digest of the vulnerability snapshot behind the adopting verdict, so the decision replays and explains itself.
	OsvSnapshot *string `json:"osvSnapshot,omitempty"`

	// Provenance The revision id that proved an internal package, minted by the pipeline that released it. Absent for external packages, which enter by policy rather than proof.
	Provenance *string `json:"provenance,omitempty"`

	// ReleasedAt When upstream published the version.
	ReleasedAt time.Time `json:"releasedAt"`

	// Source Where the artifact comes from. Registry coordinates for an external package, a git URL for an internal one.
	Source  *string `json:"source,omitempty"`
	Version string  `json:"version"`

	// Vulns Counts of known, unfixed vulnerabilities affecting one version, by severity. Vectors compare lexicographically from critical down, so a critical never trades against any number of lows. A vulnerability with unknown severity counts as high.
	Vulns SeverityVector `json:"vulns"`
}
